import React from "react";

import Table from "../../../components/Table";
import TableRow from "../../../components/Table/TableRow";
import TableHead from "../../../components/Table/TableHead";
import TableData from "../../../components/Table/TableData";
import Header from "../../../components/Header";

import "./styles.css";

const FavLots = () => {
  return (
    <div className="h-100 d-flex flex-column">
      <Header className="header--bg-white bg-white">
        <div className="d-flex flex-row align-items-center justify-content-space-between w-100">
          <span className="text-color text-semi-bold">Lorem ipsum</span>
        </div>
      </Header>

      <div className="w-100 favlots__table">
        <div className="container">
          <p className="text-description mb-15 mt-15">
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Distinctio neque ea possimus placeat nam sequi ad laudantium numquam tempore beatae atque cupiditate, assumenda porro voluptas minus reiciendis, voluptates, perferendis hic!
            Dignissimos architecto eaque quaerat voluptatibus maiores, a ad voluptate similique, alias dolorem corporis ullam id dolore adipisci sit provident nemo ut dolores aspernatur. Facere cum nostrum illo fuga incidunt itaque.
          </p>

          <div className="row">
            <div className="col-12 mb-20">
              <Table>
                <thead>
                  <TableRow>
                    <TableHead>Lorem ipsum</TableHead>
                    <TableHead>Lorem ipsum</TableHead>
                    <TableHead>Lorem ipsum</TableHead>
                    <TableHead>Lorem ipsum</TableHead>
                  </TableRow>
                </thead>
                <tbody>
                  <TableRow>
                    <TableData>1º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>2º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                </tbody>
              </Table>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default FavLots;
