import React from "react";

import Table from "../../../components/Table";
import TableRow from "../../../components/Table/TableRow";
import TableHead from "../../../components/Table/TableHead";
import TableData from "../../../components/Table/TableData";
import Header from "../../../components/Header";

import "./styles.css";

const Ranking = () => {
  return (
    <div className="h-100 d-flex flex-column">
      <Header className="header--bg-white bg-white">
        <div className="d-flex flex-row align-items-center justify-content-space-between w-100">
          <span className="text-color text-semi-bold">Ranking de clientes</span>
        </div>
      </Header>

      <div className="w-100 ranking__table">
        <div className="container">
          <p className="text-description mb-15 mt-15">
            A página de ranking destaca os clientes mais importantes, mostrando
            quem fez mais compras e o valor total delas. É uma ferramenta
            poderosa para reconhecer e agradecer seus clientes fiéis,
            identificar oportunidades de promoções e descontos especiais e
            entender melhor o comportamento de compra de seus clientes.
          </p>

          <div className="row">
            <div className="col-12 mb-20">
              <Table>
                <thead>
                  <TableRow>
                    <TableHead>Posição</TableHead>
                    <TableHead>Nome completo</TableHead>
                    <TableHead>Útimo login no usadão</TableHead>
                    <TableHead>Situação</TableHead>
                  </TableRow>
                </thead>
                <tbody>
                  <TableRow>
                    <TableData>1º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>2º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                  <TableRow>
                    <TableData>3º</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                    <TableData>Teste</TableData>
                  </TableRow>
                </tbody>
              </Table>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Ranking;
